name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Golang-CI Lint
    timeout-minutes: 10
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go environment
        run: |
          go clean -cache
          go clean -modcache
          go mod tidy
          go mod vendor
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  test:
    name: Unit test
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -race -v ./...
